### ISSUE TITLE
0.6.1 breaks divvy if no environment variables are set

### ISSUE THREAD

**Issue by afrendeiro** [databio/yacman#19]
It seems the new 0.6.1 release causes divvy to not be able to find default divvy config if no environmental variables are set. 
It seems related to https://github.com/databio/yacman/blob/master/docs/changelog.md#changed and doesn't seem like the desired behavior.
Would be nice to still be able to use divvy without environment variables set.

```
$ python3 -m venv yacman_0.6.0
$ source yacman_0.6.0/bin/activate
$ pip install yacman==0.6.0 divvy
$ divvy list
Using default config. No config found in env var: ['DIVCFG', 'PEPENV']
Using divvy config: /home/afr/Documents/workspace/toolkit/yacman_0.6.0/lib/python3.7/site-packages/divvy/default_config/divvy_config.yaml
Available compute packages:

default
docker
singularity_slurm
singularity
local
slurm
```
```
$ python3 -m venv yacman_0.6.1
$ source yacman_0.6.1/bin/activate
$ pip install yacman==0.6.1 divvy
$ divvy list

Using divvy config: None
Traceback (most recent call last):
  File "/home/afr/Documents/workspace/toolkit/yacman_0.6.1/bin/divvy", line 10, in <module>
    sys.exit(main())
  File "/home/afr/Documents/workspace/toolkit/yacman_0.6.1/lib/python3.7/site-packages/divvy/compute.py", line 429, in main
    dcc = ComputingConfiguration(filepath=divcfg)
  File "/home/afr/Documents/workspace/toolkit/yacman_0.6.1/lib/python3.7/site-packages/divvy/compute.py", line 68, in __init__
    raise Exception("Your config file is not in divvy config format (it"
Exception: Your config file is not in divvy config format (it lacks a compute_packages section)
```

**Comment by stolarczyk** [comment]
Sorry. I ran the `divvy` test suite before the release, and it passed. But I had the env var set, so it did not cover your case...

will fix it, thanks

**Comment by nsheff** [comment]
@michalstolarczyk can you add a test case to divvy that resets the env var to prevent this in the future?

**Comment by stolarczyk** [comment]
sure. In fact, I'm working on that right now

**Comment by nsheff** [comment]
Is this also going to be a problem with bulker, which also uses a config environment variable? caravel?

**Comment by nsheff** [comment]
I believe this same thing is causing this issue: https://github.com/pepkit/looper/issues/218

**Comment by stolarczyk** [comment]
it's fixed on `dev` branch now
