### ISSUE TITLE
config files never get unlocked

### ISSUE THREAD

**Issue by nsheff** [databio/yacman#22]
bulker activate databio/lab
Bulker config: /home/nsheff/Dropbox/env/bulker_config/puma.yaml
Activating bulker crate: databio/lab

nsheff@puma:~$ exit
nsheff@puma:~$ bulker activate databio/lab
Bulker config: /home/nsheff/Dropbox/env/bulker_config/puma.yaml
Waiting for file lock: /home/nsheff/Dropbox/env/bulker_config/lock.puma.yaml ....Traceback (most recent call last):
  File "/home/nsheff/.local/bin/bulker", line 10, in <module>
    sys.exit(main())
  File "/home/nsheff/.local/lib/python3.5/site-packages/bulker/bulker.py", line 501, in main
    bulker_config = yacman.YacAttMap(filepath=bulkercfg, writable=True)
  File "/home/nsheff/.local/lib/python3.5/site-packages/yacman/yacman.py", line 84, in __init__
    _make_rw(filepath, wait_max)
  File "/home/nsheff/.local/lib/python3.5/site-packages/yacman/yacman.py", line 265, in _make_rw
    _wait_for_lock(lock_path, wait_max)
  File "/home/nsheff/.local/lib/python3.5/site-packages/yacman/yacman.py", line 227, in _wait_for_lock
    raise RuntimeError("The maximum wait time has been reached and the lock file still exists.")
RuntimeError: The maximum wait time has been reached and the lock file still exists.

**Comment by nsheff** [comment]
just activate a crate, and then exit, and then try to reactivate.

the first command creates a lock file which is never removed. how can this happen? Shouldn't the lock file be removed when the object is destroyed?

**Comment by stolarczyk** [comment]
>  Shouldn't the lock file be removed when the object is destroyed?

Yes, that's what should happen. And it works as expected in a interactive session and `refgenie`

```
In [1]: from yacman import YacAttMap                                                                                                   

In [2]: y=YacAttMap(filepath="genomes.yaml",writable=True)                                                                             

In [3]: ll lock.genomes.yaml                                                                                                           
-rwxr-xr-x  1 mstolarczyk  staff  0 Oct 10 08:21 lock.genomes.yaml*

In [4]: del y                                                                                                                          

In [5]: ll lock.genomes.yaml                                                                                                           
ls: lock.genomes.yaml: No such file or directory
```

**Comment by nsheff** [comment]
I think it's something to do with bulker... because the process is replaced, the deconstructor is never called.

it's quite interesting actually. I've solved it on the bulker side.
