### ISSUE TITLE
yacman escaping backslashes

### ISSUE THREAD

**Issue by nsheff** [databio/yacman#32]
```
y2 = yacman.YacAttMap(yamldata='key: value\ ')
>>> y2
key: value\\
```

if you have a string with a backslash, python reads that in and escapes it by adding another backslash.

When you write that out with yacman, it now has 2 backslashes. Every time you read and write the backslashes are doubled.

One solution is, when we write or render the strings, we should use `print` instead of the direct value...

```
>>> y2
key: value\\
>>> y2.key
'value\\'
>>> print(y2.key)
value\
```

Or, we don't escape backslashes when reading in strings.

**Comment by nsheff** [comment]
```
>>> y2.__repr__()
'key: value\\\\'
>>> y2
key: value\\
>>> y3 = yacman.YacAttMap(yamldata=y2.__repr__())
>>> y3
key: value\\\\
>> print(y3)
key: value\\\\
```

**Comment by nsheff** [comment]
I think this may be the culprit:

https://github.com/pepkit/attmap/blob/54b943e597023c8dd6eac8e22b9f210ba8e60517/attmap/_att_map_like.py#L205-L228

**Comment by nsheff** [comment]
@vreuter do you have any insight into why this is happening?

**Comment by nsheff** [comment]
@vreuter I was wondering if you had a minute to take a quick look at this -- might be something you can immediately see that I am not...

**Comment by nsheff** [comment]
@stolarczyk or @vreuter  if you have a moment to look at this it would be helpful -- there are a few bulker things that depend on this

**Comment by stolarczyk** [comment]
I think I got it, is this the behavior that you were looking for, @nsheff?

```python
In [1]: from yacman import YacAttMap                                                                 

In [2]: y=YacAttMap(yamldata='key: value\ ')                                                         

In [3]: y.to_dict()                                                                                  
Out[3]: {'key': 'value\\'}

In [4]: pth = "test.yml"                                                                            

In [5]: y.write(filepath=pth)                                                                        
Out[5]: '/Users/mstolarczyk/Desktop/testing/test.yml'

In [6]: del y                                                                                        

In [7]: y=YacAttMap(filepath=pth)                                                                    

In [8]: y.to_dict()                                                                                  
Out[8]: {'key': 'value\\'}

In [9]: !cat $pth                                                                                    
key: value\
```

The backslashes are not doubled anymore

**Comment by nsheff** [comment]
what happens when you do just:

```python
y=YacAttMap(yamldata='key: value\ ')         
y
```

or
```
y.key
```

Because I need to use the value from within python. You seem to have shown that you can use `.write` to get it out and it does that correctly, but what about a use that does not go through `.write` ?

**Comment by stolarczyk** [comment]
the result of the first snippet is:

```python
In [3]: y=YacAttMap(entries={"key": "value\ "})             
   ...: y                                                                                            
Out[3]: key: value\
```

the result of the second one is:

```python
In [17]: y=YacAttMap(entries={"key": "value\ "})                                                     

In [18]: y['key']                                                                                    
Out[18]: 'value\\ '
```

So not what you expected, but I thought that this is how we wanted it to be. It follows the built-in `dict` behavior: 

```python
In [19]: x={"key": "value\ "}                                                                        

In [20]: x['key']                                                                                    
Out[20]: 'value\\ '
```

**Comment by nsheff** [comment]
Ok, interesting... did you change anything then? Should I try if bulker works with the dev yacman?

**Comment by stolarczyk** [comment]
I made some changes, but didn't push them yet. I'll do this now

**Comment by stolarczyk** [comment]
the change is in attmap repo, try installing from attmap@dev and use released yacman

**Comment by nsheff** [comment]
I think this is working fine.

In my original use case, the solution turned out to be using single-quoted strings in the yaml file if I don't want them to get dual-escaped.
