### ISSUE TITLE
wait time

### ISSUE THREAD

**Issue by nsheff** [databio/yacman#34]
Running on generating 20 or so fasta archives simultaneously I get a lot of failures with this error:

```
Waiting for file lock: /project/shefflab/deploy/rg.databio.org/refgenomes.databio.org/config/lock.refgenie_config.yaml ....Tracebac
k (most recent call last):                                                                                                         
  File "/home/ns5bc/.local/bin/refgenie", line 10, in <module>                                                                     
    sys.exit(main())                                                                                                               
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenie/refgenie.py", line 639, in main                                    
    refgenie_build(gencfg, asset_list[0]["genome"], asset_list, recipe_name, args)                                                 
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenie/refgenie.py", line 491, in refgenie_build                          
    specified_args, specified_params, **input_assets):                                                                             
  File "/home/ns5bc/.local/lib/python3.6/site-packages/refgenie/refgenie.py", line 419, in build_asset                             
    with rgc as r:                                                                                                                 
  File "/home/ns5bc/.local/lib/python3.6/site-packages/yacman/yacman.py", line 116, in __enter__                                   
    self.make_writable()                                                                                                           
  File "/home/ns5bc/.local/lib/python3.6/site-packages/yacman/yacman.py", line 222, in make_writable                               
    _make_rw(filepath, getattr(self, WAIT_MAX_KEY, DEFAULT_WAIT_TIME))                                                             
  File "/home/ns5bc/.local/lib/python3.6/site-packages/yacman/yacman.py", line 335, in _make_rw                                    
    _wait_for_lock(lock_path, wait_max)                                                                                            
  File "/home/ns5bc/.local/lib/python3.6/site-packages/yacman/yacman.py", line 297, in _wait_for_lock                              
    raise RuntimeError("The maximum wait time has been reached and the lock file still exists.")                                   
RuntimeError: The maximum wait time has been reached and the lock file still exists. 
```

Suggestions:
- increase max wait time?
- but 10 seconds of waiting seems it should be plenty...so maybe it's something about frequency of checking? In this case it's not 1 process that's locking it out, it's 30 processes that all want to write at the same time. Each one should be really fast.

**Comment by nsheff** [comment]
Looking at the sleep time calculation, and the logs, there are only 4 dots, so it only checks 4 times in the 10 second period... probably frequency of checking would help a lot.

**Comment by nsheff** [comment]
I think maybe the bigger picture problem is that refgenie should not open the file in rw mode at first... maybe?

**Comment by stolarczyk** [comment]
- the line numbers in the error traceback do not correspond to the dev version of refgenie, so please switch to that one. I don't expect it to fix this issue, but it is compatible with dev refgenconf, which you're probably using

- the problem of overly long locking stems from this context manager. All the steps inside it are just simple writes, except for one (marked with `-->`). It calculates a digest of the directory. So in case of a large FASTA file it can take considerable time. Possibly over 10s, which is the max wait time in this case. 

            with rgc as r:
                r.update_assets(*gat[0:2], data={CFG_ASSET_DESC_KEY: build_pkg[DESC]})
                r.update_tags(*gat, data={CFG_ASSET_PATH_KEY: asset_key})
                r.update_seek_keys(*gat, keys={k: v.format(**asset_vars) for k, v in build_pkg[ASSETS].items()})
                # in order to conveniently get the path to digest we update the tags metadata in two steps
                --> digest = get_dir_digest(_seek(r, genome, asset_key, tag, enclosing_dir=True), pm) 
                r.update_tags(*gat, data={CFG_ASSET_CHECKSUM_KEY: digest})
                _LOGGER.info("Asset digest: {}".format(digest))
                r.set_default_pointer(*gat)

So a possible solution is to split this context manager in two with `get_dir_digest` between them, like so:

            with rgc as r:
                r.update_assets(*gat[0:2], data={CFG_ASSET_DESC_KEY: build_pkg[DESC]})
                r.update_tags(*gat, data={CFG_ASSET_PATH_KEY: asset_key})
                r.update_seek_keys(*gat, keys={k: v.format(**asset_vars) for k, v in build_pkg[ASSETS].items()})
                # in order to conveniently get the path to digest we update the tags metadata in two steps

           digest = get_dir_digest(_seek(rgc, genome, asset_key, tag, enclosing_dir=True), pm) 
           with rgc as r:
                r.update_tags(*gat, data={CFG_ASSET_CHECKSUM_KEY: digest})
                _LOGGER.info("Asset digest: {}".format(digest))
                r.set_default_pointer(*gat)

**Comment by nsheff** [comment]
yes. we should definitely take the digest out of the waiting period. I believe your solution would work. 

Even better would be to get the path the hard way instead of requiring an update tags twice, maybe, which would reduce the number of file locks from 2 to 1, which is desirable.

**Comment by nsheff** [comment]
Hi @stolarczyk that change is going to solve the problem and make it much better, thanks! Do you think while we're changing this, it would be possible to just make it only write once? Not sure how difficult that will be...

**Comment by stolarczyk** [comment]
Yes, that’s possible. We’d need to just string together genome dir, genome name, asset name and tag name to get the path for digest calculation. 
The reason I don’t like it is that’s not a sustainable solution; if we happened to change the asset directory structure we would need to update this part as well. RefGenConf.seek takes care of that, as it’s built for exactly this reason. 

But if you think the double write a bigger issue we can go with the duplicated implementation of seek here

**Comment by nsheff** [comment]
You're right, I like the seek idea for the reason you mentioned... can you use seek without writing it? 
like, update the object, then use seek... *then* write?

**Comment by stolarczyk** [comment]
The answer is — yes.  Unfortunately, I don’t see how it would solve the issue. To use the seek method the genome and asset need to be defined in RefGenConf. First 3 lines in the context manager pasted above add them to the object. So in order to lock the file only once we would need to make the updates before entering the context manager, use seek, calculate the digest and then just lock it once for writing. But the reason we lock the file in the first place is to safely perform these updates.

**Comment by nsheff** [comment]
It seems like it would be possible to:

1. update the conf object *in memory* (but not on disk) with the new info (maybe a `deepcopy` of it?)
2. use this to look up the asset location with seek
3. use this to compute the digest
4. lock the file
5. update the conf with the original in memory updates, *and* the digest update
6. write the file
7. unlock the file.

**Comment by stolarczyk** [comment]
just implemented this with a small tweak in 1. -- instead of copying the object I'm creating a temporary, empty one with just the metadata needed to get the path.
