### ISSUE TITLE
optional jsonschema validation 

### ISSUE THREAD

**Issue by stolarczyk** [databio/yacman#42]
I found myself implementing jsonschema validation in two children of `YacAttMap`. Maybe we could implement this feature here?

I propose we add an _optional_ `schema_path` argument to `YacAttMap` constructor, which will read the schema in and validate the config, if provided.

any objections?

**Comment by stolarczyk** [comment]
By extension, it could also provide an option to validate the config prior to _writing_. An example use case would be genome config validation in refgenie, which would prevent issues like this one: https://github.com/refgenie/refgenconf/issues/115

**Comment by nsheff** [comment]
I like this idea.
