### ISSUE TITLE
PEP schema error from yacman (and peppy) - urllib.error.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by rcorces** [databio/yacman#59]
I'm pretty sure this is most relevant to post here but I think it also affects `peppy` as described at the end.
Is it possible that something recently changed related to security on the schema.databio.org side of things?
All of a sudden, our PEPATAC pipelines wont run because of an `Error 403: Forbidden` when yacman or peppy try to open what I think is the PEP 2.0 schema hosted at http://schema.databio.org/pep/2.0.0.yaml

My assumption is that this is because something on your server side is assuming that the request comes from a bot as suggested here:
https://stackoverflow.com/questions/16627227/problem-http-error-403-in-python-3-web-scraping

A minimal reproducible example of this in python3:
```
from urllib.request import urlopen
response = urlopen("http://schema.databio.org/pep/2.0.0.yaml")
```
This yields:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

If instead, you set a known browser agent, it works just fine:
``` 
from urllib.request import Request, urlopen
req = Request(
    url='http://schema.databio.org/pep/2.0.0.yaml', 
    headers={'User-Agent': 'Mozilla/5.0'}
)
webpage = urlopen(req).read()
```

below is truncated for display purposes
```
>>> webpage
b'description: "Schema for a minimal PEP"\nversion: "2.0.0"\nproperties:\n
```

On my end, this is fixed by editing the yacman code here:

https://github.com/databio/yacman/blob/9c5824903fa0f9d5399882fcd5c456c02726df72/yacman/yacman.py#L421-L437

To be:
```
    if is_url(filepath):
        _LOGGER.debug(f"Got URL: {filepath}")
        try:  # python3
            from urllib.error import HTTPError
            from urllib.request import Request, urlopen
        except:  # python2
            from urllib2 import URLError as HTTPError
            from urllib2 import urlopen
        try:
            req = Request(
                        url=filepath,
                            headers={'User-Agent': 'Mozilla/5.0'}
                            )
            response = urlopen(req)
        except HTTPError as e:
            raise e
        data = response.read()  # a `bytes` object
        text = data.decode("utf-8")
        return yaml.safe_load(text)
    else:
        return read_yaml_file(filepath)
```

For what its worth, this also appears to be a problem that will crop up in `peppy` here:
https://github.com/pepkit/peppy/blob/cac87fb91958d77f89c7ad76108c2efbf67a58e6/peppy/utils.py#L120

**Comment by nsheff** [comment]
Turns out, this was a problem with some DNS settings I changed a few days ago. I changed it back, and things should work again.

See: https://github.com/pepkit/eido/issues/52

But thanks for posting the solution here, I may change this so that this won't be a problem again in the future.
